"""add standup fk in submission

Revision ID: 0294d6131dc3
Revises: 540bd398b646
Create Date: 2021-05-09 11:18:03.354158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0294d6131dc3'
down_revision = '540bd398b646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standup_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_submission_standup_id_standup', 'standup', ['standup_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('standup_id')

    # ### end Alembic commands ###
