"""empty message

Revision ID: 348edda30d8f
Revises: 361a98f929fb
Create Date: 2021-07-15 17:25:04.674264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348edda30d8f'
down_revision = '361a98f929fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_submit_action', sa.Enum('cat', 'dog', 'none', name='postsubmitactionenum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('post_submit_action')

    # ### end Alembic commands ###
