"""add publish channel

Revision ID: 540bd398b646
Revises: 
Create Date: 2021-05-08 21:00:35.959006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540bd398b646'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish_channel', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standup', schema=None) as batch_op:
        batch_op.drop_column('publish_channel')

    # ### end Alembic commands ###
