"""empty message

Revision ID: c235bc96c11d
Revises: 348edda30d8f
Create Date: 2021-07-15 18:10:42.944469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c235bc96c11d'
down_revision = '348edda30d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standup', schema=None) as batch_op:
        batch_op.drop_column('publish_time')

    # ### end Alembic commands ###
